name: Run Python Tests

on:
  push:
    branches: [ "**" ]     # run on all pushes
  pull_request:             # also run on PRs

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Verify Python version
        run: python --version  
        
      # Cache uv's package cache between runs
      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ matrix.python-version }}-        

      - name: Install uv
        run: pip install uv

      - name: Install dependencies with uv
        run: uv pip install -r requirements.txt --system

      - name: Install project in editable mode
        run: uv pip install -e . --system

      - name: Run unit tests 
        run: PYTHONPATH=. pytest -v -m "unit" --maxfail=1 --disable-warnings

      - name: Run integration tests 
        run: PYTHONPATH=. pytest -v -m "integration" --maxfail=1 --disable-warnings


        