name: Run Python Unit Tests

on:
  push:
    branches: [ "**" ]     # run on all pushes
  pull_request:             # also run on PRs

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: pip install uv

      - name: Install dependencies with uv
        run: uv pip install -r requirements.txt --system

      - name: Install project in editable mode
        run: uv pip install -e . --system

      - name: Run unit tests with pytest
        run: PYTHONPATH=src pytest -v --maxfail=1 --disable-warnings
        